// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.zzsong.netty.grpc.hello;

public interface CatReplyListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zzsong.netty.grpc.hello.CatReplyList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.zzsong.netty.grpc.hello.CatReply catReply = 1;</code>
   */
  java.util.List<com.zzsong.netty.grpc.hello.CatReply> 
      getCatReplyList();
  /**
   * <code>repeated .com.zzsong.netty.grpc.hello.CatReply catReply = 1;</code>
   */
  com.zzsong.netty.grpc.hello.CatReply getCatReply(int index);
  /**
   * <code>repeated .com.zzsong.netty.grpc.hello.CatReply catReply = 1;</code>
   */
  int getCatReplyCount();
  /**
   * <code>repeated .com.zzsong.netty.grpc.hello.CatReply catReply = 1;</code>
   */
  java.util.List<? extends com.zzsong.netty.grpc.hello.CatReplyOrBuilder> 
      getCatReplyOrBuilderList();
  /**
   * <code>repeated .com.zzsong.netty.grpc.hello.CatReply catReply = 1;</code>
   */
  com.zzsong.netty.grpc.hello.CatReplyOrBuilder getCatReplyOrBuilder(
      int index);
}
