// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.zzsong.netty.grpc.hello;

public interface CatReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zzsong.netty.grpc.hello.CatReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string category = 1;</code>
   * @return The category.
   */
  java.lang.String getCategory();
  /**
   * <code>string category = 1;</code>
   * @return The bytes for category.
   */
  com.google.protobuf.ByteString
      getCategoryBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 3;</code>
   * @return The age.
   */
  int getAge();
}
