// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.zzsong.netty.grpc.hello;

public interface CatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zzsong.netty.grpc.hello.CatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string category = 1;</code>
   * @return The category.
   */
  java.lang.String getCategory();
  /**
   * <code>string category = 1;</code>
   * @return The bytes for category.
   */
  com.google.protobuf.ByteString
      getCategoryBytes();
}
