// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.zzsong.netty.grpc.hello;

public final class HelloWorldServer {
  private HelloWorldServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zzsong_netty_grpc_hello_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zzsong_netty_grpc_hello_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zzsong_netty_grpc_hello_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zzsong_netty_grpc_hello_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020helloworld.proto\022\033com.zzsong.netty.grp" +
      "c.hello\"\034\n\014HelloRequest\022\014\n\004name\030\001 \001(\t\"\035\n" +
      "\nHelloReply\022\017\n\007message\030\001 \001(\t2\322\001\n\007Greeter" +
      "\022`\n\010SayHello\022).com.zzsong.netty.grpc.hel" +
      "lo.HelloRequest\032\'.com.zzsong.netty.grpc." +
      "hello.HelloReply\"\000\022e\n\rSayHelloAgain\022).co" +
      "m.zzsong.netty.grpc.hello.HelloRequest\032\'" +
      ".com.zzsong.netty.grpc.hello.HelloReply\"" +
      "\000B3\n\033com.zzsong.netty.grpc.helloB\020HelloW" +
      "orldServerH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_zzsong_netty_grpc_hello_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zzsong_netty_grpc_hello_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zzsong_netty_grpc_hello_HelloRequest_descriptor,
        new String[] { "Name", });
    internal_static_com_zzsong_netty_grpc_hello_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_zzsong_netty_grpc_hello_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zzsong_netty_grpc_hello_HelloReply_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
