// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.zzsong.netty.grpc.hello;

public interface PersonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zzsong.netty.grpc.hello.PersonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sex = 1;</code>
   * @return The sex.
   */
  int getSex();
}
